### ISSUE TITLE
Sometimes random crashes and sends owned game

### ISSUE THREAD

**Issue by ArtiomkaPL** [frej4189/steam-games-bot#1]
I tested it with gems and it sent me a games I owned 4 times in row, it means its broken. Also sometimes it randomly crashes.

**Comment by frej4189** [comment]
Is your game info or profile private? Might be causing the thing with the owned games.

I would like to see the logs for the crashes, can't do anything about it before then

**Comment by frej4189** [comment]
Can not load data of new games, probably the cause of error with sending owned games.

Random crashes should be fixed by now.
