### ISSUE TITLE
Bot Bugged

### ISSUE THREAD

**Issue by mbrandao-dev** [frej4189/steam-games-bot#2]
Hi, first of all, thank you for taking your time creating this script and putting it here.

Well, as it come to my attention, more people are having this problem too, and I´m trying to open a games bot, so I opened this thread.

Basically, the bot has for exemple 100 games in stock. Than I buy for example 50 games, in the moment I write the !buy command the bot exclueds the 50 games from the "non-steam game". It´s ok, he b asically "saves" so others will not get the same games.

But if I write !cancel or refuse the trade offer, it keeps saying that has 50 games, instead of the 100.

And also, it is giving some codes more than one time.

Ty for the attention,

IceTapz

**Comment by frej4189** [comment]
Hey, I believe to have fixed this issue some time ago, please open a new ticket if not.
